apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yj2evci2k-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:af1fab59df9f9cc044d986cfa3f8e85729fb3821@sha256:6eb0d03cd183627e5a8c68c8eb58a6ff3a84dd05683d4a64c964a67667283c15
          name: container-image
